from sqlalchemy import select

from app.core.config import settings
from app.core.database import SessionLocal
from app.core.security import hash_password
from app.models import AuditLog, ExamTemplate, Module, Question, QuestionPaper, QuestionPaperItem, Settings, Subject, User


SUBJECTS = [
    ("CS501", "Artificial Intelligence"),
    ("CS502", "Database Systems"),
    ("CS503", "Computer Networks"),
    ("CS504", "Software Engineering"),
    ("CS505", "Data Structures"),
    ("CS506", "Operating Systems"),
]

MODULE_TITLES = [
    "Foundations and Core Concepts",
    "Design Methods and Algorithms",
    "Applied Systems and Evaluation",
]

BLOOM_LEVELS = ["Remember", "Understand", "Apply", "Analyze", "Evaluate", "Create"]
DIFFICULTIES = ["Easy", "Medium", "Hard"]
MARKS = [2, 5, 10]


def seed_demo_data() -> None:
    with SessionLocal() as db:
        existing_user = db.scalar(select(User).where(User.username == settings.default_admin_username))
        if existing_user is not None:
            return

        admin = User(
            username=settings.default_admin_username,
            email=settings.default_admin_email,
            full_name="ExamForge Administrator",
            password_hash=hash_password(settings.default_admin_password),
            role="admin",
        )
        db.add(admin)

        db.add(
            Settings(
                institution_name=settings.default_institution_name,
                similarity_threshold=int(settings.similarity_threshold * 100),
                default_instructions="Answer all questions. Draw neat diagrams wherever required.",
            )
        )

        subjects: list[Subject] = []
        modules: list[Module] = []
        for code, name in SUBJECTS:
            subject = Subject(
                code=code,
                name=name,
                description=f"Curated question bank for {name} at {settings.default_institution_name}.",
            )
            subjects.append(subject)
            db.add(subject)
            db.flush()
            for index in range(1, 4):
                if len(modules) >= 15:
                    break
                module = Module(
                    subject_id=subject.id,
                    title=f"{name}: {MODULE_TITLES[index - 1]}",
                    order_index=index,
                )
                modules.append(module)
                db.add(module)

        db.flush()

        for number in range(200):
            module = modules[number % len(modules)]
            subject_id = module.subject_id
            bloom = BLOOM_LEVELS[number % len(BLOOM_LEVELS)]
            difficulty = DIFFICULTIES[number % len(DIFFICULTIES)]
            marks = MARKS[number % len(MARKS)]
            topic = module.title.split(": ", maxsplit=1)[-1].lower()
            db.add(
                Question(
                    subject_id=subject_id,
                    module_id=module.id,
                    text=(
                        f"{bloom} the key principles of {topic} and demonstrate their "
                        f"application in a realistic university assessment scenario #{number + 1}."
                    ),
                    marks=marks,
                    difficulty=difficulty,
                    bloom_level=bloom,
                    question_type="descriptive",
                    keywords=f"{topic}, {bloom.lower()}, assessment",
                    model_answer="A complete answer should include definitions, reasoning, examples, and evaluation.",
                    usage_count=number % 9,
                )
            )

        templates = [
            ("Mid Semester", 90, 40, 3),
            ("End Semester", 180, 100, 5),
            ("Quiz", 30, 20, 2),
            ("Assignment", 1440, 50, 4),
            ("Lab Test", 120, 60, 3),
        ]
        for name, duration, marks, sections in templates:
            db.add(
                ExamTemplate(
                    name=name,
                    duration_minutes=duration,
                    total_marks=marks,
                    sections=sections,
                    instructions="Generated by ExamForge AI with balanced Bloom and difficulty coverage.",
                )
            )

        db.flush()
        questions = db.scalars(select(Question).limit(50)).all()
        for paper_index in range(5):
            subject = subjects[paper_index % len(subjects)]
            paper = QuestionPaper(
                title=f"{subject.name} Sample Paper {paper_index + 1}",
                subject_id=subject.id,
                total_marks=40 + paper_index * 10,
                duration_minutes=90 + paper_index * 15,
                status="published",
                generated_by=admin.id,
            )
            db.add(paper)
            db.flush()
            for sequence, question in enumerate(questions[paper_index * 5 : paper_index * 5 + 5], start=1):
                db.add(
                    QuestionPaperItem(
                        paper_id=paper.id,
                        question_id=question.id,
                        section=chr(64 + sequence),
                        sequence=sequence,
                        marks=question.marks,
                    )
                )

        db.add(
            AuditLog(
                actor="system",
                action="seed_demo_data",
                entity="database",
                detail="Created admin user, 6 subjects, 15 modules, 200 questions, and 5 sample papers.",
            )
        )
        db.commit()
